name: "fsw1"
interval: 5
prober:
  object_size: 4096
  type: "write"
pool_name: "watchdog"
image_name: "foo"
rbd_user: "watchdog"
rbd_keyring_path: "/etc/ceph/ceph.client.watchdog.keyring"
monitors:
  - 192.168.51.181
  - 192.168.51.182
  - 192.168.51.183
histogram_buckets:
  - 0
  - 0.2
  - 0.5
  - 0.7
  - 1.0
  - 2.0
  - 5.0
