name: test

on:
  - push
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y librbd-dev python3-rbd librados-dev python3-rados
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          export "PATH=/home/runner/.local/bin:$PATH"
          pytest
  behave:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test with behave
        run: behave tests/behave/features
